### ISSUE TITLE
ModuleNotFoundError: No module named 'gpu_mem_track'

### ISSUE THREAD

**Issue by 331801070049** [Oldpan/Pytorch-Memory-Utils#6]
Where to put the decompression file? Prompt me after running: Modulenotfounderror:no module named ' Gpu_mem_track 'Thank you

**Comment by 331801070049** [comment]
A new problem, the following error occurred: OSError: [Errno] Invalid argument: ' 17-Apr-19-17:58:11-gpu_mem_track.txt '

**Comment by Oldpan** [comment]
Maybe your path is wrong. Did you run this code in windows?

**Comment by 331801070049** [comment]
> Maybe your path is wrong. Did you run this code in windows?
I have solved this problem and can run under Windows. Thank you very much for the code you provided.

**Comment by 331801070049** [comment]
I have solved this problem and can run under Windows. Thank you very much for the code you provided.

**Comment by Licko0909** [comment]
Prerequisite: 
1、ubuntu 16
2、This command has been executed.
`pip install nvidia-ml-py3`

I also have the same problem, originally a hint:
`ModuleNotFoundError: No module named 'gpu_mem_track'`

Later I cloned your github code and solved the above problem.

However, the following problems have occurred:
![image](https://user-images.githubusercontent.com/27897166/60076378-faf8be80-9759-11e9-8d78-d1439bce8b02.png)

Is it that I am using it incorrectly?
